### ISSUE TITLE
Certified exploration charms/bundles

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/charmhub.io#102]
Consider how we will showcase all the types below within the details page:

- Featured category: These are hand picked "things" that we want to promote
- Featured flag: these are hand picked "things" that we want to promote in categories other than "featured category"
- Verified publishers: currently in snapcraft - we say "we trust this publisher"
- Certified charms: what I think people want in charmhub - we say "this charm is of good quality"

**Comment by cristinadresch** [comment]
@Lukewh @danielmutis I think this is the one right? I will put it in iteration backlog

**Comment by danielmutis** [comment]
Here is an example of how this may look like. It would be using the same certified icon that we use for charmers, but next to the charm name. If the user clicks on the icon it would expand a modal similar to the channel map with a summary of some of the values/requirements of a certified charm, with a link to the manifesto to learn more. Icons and text are placeholders. @cristinadresch 

![Certified Charm.jpg](https://images.zenhubusercontent.com/5e1c5367f4dbe2bfe4c77ad8/7cccd9c4-3413-4f0c-a5a4-a59cd27257f1)

**Comment by cristinadresch** [comment]
@danielmutis @Lukewh luke and I were just discussing the different scenarios that could be. maybe we should try to design how we would represent each in the details? check the description of this issue, I just updated it. 

Because with that in mind, I think we need to decide if we are using the tick to highlight 'Verified publishers' or 'Certified charm', and would we show here in the detail if this charm was being featured in the store page for example, or if this was within a featured category? Maybe no need to display those in this level.

**Comment by Lukewh** [comment]
I think this is good to show Sohini and gather feedback about the "Certified" part of the story.

**Comment by spencerbygraves** [comment]
I think we would need to look at the icons. I'm not sure the certified icon says click on me to find out more.

As there is more than one verified thing, perhaps we can show it differently.

CERTIFIED :white_check_mark:
Charm :question:
Publisher :question:

**Comment by cristinadresch** [comment]
Just an update here that I sent this to Sohini now together with the definition of the different terms to get a confirmation from her

**Comment by Lukewh** [comment]
@cristinadresch can you add me to that thread please?

**Comment by cristinadresch** [comment]
Sorry just pinged her on telegram, but good shout I can send out an email to make sure everyone is in the loop
