### ISSUE TITLE
Add Relations tab to Charm page

### ISSUE THREAD

**Issue by heitorPB** [canonical-web-and-design/charmhub.io#1068]
It would be very useful to have a `Relations` tab, just after `Actions` tab, in the Charmhub page for a charm.

This is particularly important for database charms. Of course we should always read the documentation, but sometimes we want a quick table to skim the relation and currently do not have a way for that.

**Comment by danielmutis** [comment]
@heitorPB thanks for creating this issue. We are aware that displaying what endpoints can be used to relate to a charm is very important to be able to consume them, and we have already done some designs to include a relations tab. In these designs we plan to show what charms you can relate to with the current charm you are viewing, as well as what endpoints and interfaces can be used to do so. Currently the engineering teams are working on developing the APIs that are needed in order to have this on the website, and this page will be available soon.

**Comment by heitorPB** [comment]
That's great! Do you have an idea of when this will be available?

**Comment by heitorPB** [comment]
Oh, this issue a duplicate of #1049 ?

**Comment by danielmutis** [comment]
The APIs should be ready for the end of this cycle (October) so I imagine sometime early next cycle. @heitorPB
