### ISSUE TITLE
Making updates/changes to some docs bumps them up in Discourse

### ISSUE THREAD

**Issue by tmihoc** [canonical-web-and-design/charmhub.io#1126]
I'll be making a lot of small changes to the documents in the coming days. I think these shouldn't be bumped up in Discourse as this will just unnecessarily clutter the view for folks who want to see the latest discussions  there.

**Comment by anthonydillon** [comment]
Sorry @tmihoc, I don't understand the request here. Do you want to make docs updates and not have them go live?

**Comment by tmihoc** [comment]
@anthonydillon If you go to https://discourse.charmhub.io/, you will see these posts: "Use the client", "Use the Web CLI", "Use the dashboard", "Equinix Metal". These are all posts where I edited the title yesterday. Insofar as I can see, it was these small edits that caused these posts to be displayed on Discourse now. If this is indeed the reason, then I think something should change---small edits like this shouldn't be triggering post bumps in Discourse, or else they'll just clutter the forum unnecessarily. I'm particularly concerned because I'll be making lots of small and big changes in the coming days and weeks as I revise and restructure the content. PS1 I noticed that not all the posts where I made changes were bumped. PS2 I understand that bumping a post when it has new content might be useful for feedback. Not sure how to preserve this while also avoiding clutter.

**Comment by anthonydillon** [comment]
I see, at first it seems obvious. Discourse should allow "Edit without bump" option when submitting a change. It seems [this feature has been requested](https://meta.discourse.org/t/no-bump-option-when-editing-last-post-in-a-topic/170012) a number of times, without that solution being settled on. I believe the best cause of action would be to make you admin which would allow you to edit the bump date of a post after posting your edits. Although that could be frustrating across many topics.

After thinking about this a little. Is bumping docs edits a bad thing for the community? It demonstrates a living, heathy project with active docs maintenance. I can see that a typo fix would be a little noisy but is that the level of edits you are doing?

I guess, what I'm saying is that new content should be bumped. Regardless to it's perceived importance as it could and probably is of interests to the community.

**Comment by tmihoc** [comment]
"I guess, what I'm saying is that new content should be bumped. Regardless to it's perceived importance as it could and probably is of interests to the community." >> Ultimately, I agree. I can try to keep the noise level to a minimum by making multiple edits at once. That might not always be possible, as revision and restructuring is a messy process. But, as you say, that in itself might be of interest to some. So, not a bug---a _feature_.

**Comment by jkfran** [comment]
Hi @tmihoc ,

I am going to close this issue as it is not actionable for us. Thank you for reporting it. If this feature is ever available on Discourse, we could take a look into it. Please feel free to reopen.

**Comment by mcjaeger** [comment]
Hi, actually I was wondering about the same today and occasions before: how about skipping some of the doc updates which are always placed at the top of the list?

On some days, the entire displayed list appeared to be full of doc updates, but in fact, I am more interested about postings which are non-doc to check if I could contribute to a discussion. please note that most of the time I am using a notebook display.

of course, it does not appear as serious problem, because you can scroll down.

but then: the listing of posts is also mixed with a lot of doc update bumps. As explained above, it is good to have these updates also visible so persons can have a look, but I guess that would be more important for relevant updates?

by my impression it is a useful feature to allow the author to opt-out bumping (while it is by default enabled). For example the top of the list today is a "four-word-clarification-addition" to an existing document (https://discourse.charmhub.io/t/about-charms-by-development-framework/5589) where opt out could be also an option.
