### ISSUE TITLE
Charmhub.io Libraries - Side nav doesn’t represent the folder structure as intended in the design

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/charmhub.io#1188]
this was designed and signed off but never got implemented.

check [design](https://app.zeplin.io/project/5f92a9530029eeac84ae9589/screen/601928c0780bfe0acf316da6)

**Comment by cristinadresch** [comment]
@anasereijo @AnnSoMuller API is currently blocking this one, just wondering if you knew that or maybe we are unsure of this issue?

**Comment by anasereijo** [comment]
> @anasereijo @AnnSoMuller API is currently blocking this one, just wondering if you knew that or maybe we are unsure of this issue?

Oh, I thought the API was ready for this, thanks for letting us know @cristinadresch. Should we move this back to icebox or will this be ready to be worked on next iteration?

**Comment by AnnSoMuller** [comment]
This issue is about having Charms+the name of the charm in the navigation and then the different versions as sub categories. 
<img width="365" alt="Screenshot 2021-12-08 at 21 01 02" src="https://user-images.githubusercontent.com/32699582/145276140-7b55d1b4-2f9a-47c1-9f3a-b2d6a7f4030f.png">
That can't be done because of API? We didn't know that

**Comment by cristinadresch** [comment]
We spoke to Daniel Manrique about this and they don't find this solution necessary or feasible
