### ISSUE TITLE
Mobile designs: Integrations

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/charmhub.io#119]

**Comment by danielmutis** [comment]
Mobile designs of the integrations view [here](https://zpl.io/2yrYNLq).

**Comment by steverydz** [comment]
As discussed in standup, there was a solution proposed to use an accordion rather than a carousel for this. Ideally it would be good to use an existing component but I don't think the structure of what we're trying to display would work with an accordion.

It would be good if the desktop and mobile versions had more in common with each other as the desktop version is proving to be very complicated to build in a dynamic way, and this version will have to be a separate chart on the page which isn't ideal.

**Comment by danielmutis** [comment]
The problem with the mobile version is that it's hard to make it fit vertically. Maybe we could make them rotate the phone to see this feature? I think accordion wouldn't be ideal and would make the interaction strange.

**Comment by steverydz** [comment]
I definitely don't think we should force the user to rotate their device. I think vertical is fine and they can always scroll as long as it's obvious there is something to scroll to.

My concern is more about the two versions of the chart having very little in common which means one will have to be hidden in either view, and also be built using different technologies. The mobile chart can be built with CSS whereas the desktop one requires a library such as d3 due to the complex nature of showing the multiple integrations.

Would it not be more reasonable to have a horizontal version of the mobile chart with a carousel? That would also scale better if there are several integrations.

**Comment by anthonydillon** [comment]
It's nice to keep the same component but on the phone the most important thing is likely the information. Quick and in a simple format. Why not just switch the chart out for a table or definition list which would show all the data in one screen and be clear for small screen users? Much simpler to build and no waste of effort of we change later.

**Comment by steverydz** [comment]
The mobile chart works fine, possibly better than a table because it could get quite wide depending on the number of integrations. I actually think the mobile chart works well for desktop too.

![Screenshot from 2020-10-28 11-32-08](https://user-images.githubusercontent.com/501889/97430771-42c0c480-1911-11eb-863d-42f4ddf0e47d.png)

**Comment by hatched** [comment]
There is a lot of wasted space on the sides on the desktop.

You could take advantage of that by expanding the integration types out until it runs out of space then converting it to a carousel when necessary.
