### ISSUE TITLE
Icon not being displayed on charms not yet released to stable.

### ISSUE THREAD

**Issue by PietroPasotti** [canonical-web-and-design/charmhub.io#1356]
There seems to be an issue that charms that are released to edge don't have their icon display on charmhub.
For example, at the time of writing, this charm https://charmhub.io/traefik-route-k8s has an icon.svg at its root that (to the best of my knowledge) satisfies all specs and guidelines, and yet won't show.
Source: https://github.com/PietroPasotti/traefik-route-k8s-operator

I've been told that a workaround is to release the charm to stable, then ask someone to roll that back, and that will have the icon display. That however feels... wrong.

**Comment by jkfran** [comment]
Hello Pietro, @Roadmaster confirmed with us that it is like this by design. He also told us the trick you are mentioning here, which is to release to stable and the close stable if you don't want to have a release on stable.

In any case, this is the repository for the Charmhub website. To report this issue to the store team, I think you need to use: https://bugs.launchpad.net/snapstore-server/+filebug

**Comment by PietroPasotti** [comment]
Got it, thanks!
