### ISSUE TITLE
If I search for a charm that returns one result, can I just be taken to the page for that charm?

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/charmhub.io#632]
Currently if I search for a charm that I know there's only one of in charmhub (such as "mattermost"), I get one result. Would it not be better to just send me directly to the page for mattermost rather than show me a list of one result?

**Comment by tbille** [comment]
This sounds like a good idea.

I think it should match **exactly** the charm name so it's not too confusing. @danielmutis what do you think?

**Comment by danielmutis** [comment]
I understand you believe this would be time-saving as it spares you one click; however, I am not sure the expected behaviour on a search bar like the one we have would be for it to load the charm page directly (even if there is only one result). If the search results were showing you matching suggestions and you clicked on one of those I would understand that this is an expected behaviour, but in our case I think it can be confusing.
