### ISSUE TITLE
Search result page is a separate view from the main store page

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/charmhub.io#721]
Searching a term on charmhub.io returns to a search result page:
<img width="1223" alt="Screenshot 2020-12-09 at 17 58 52" src="https://user-images.githubusercontent.com/1953388/101668261-366b7380-3a48-11eb-9a31-c2b818f39888.png">

As a user I cannot see what these results are for (e.g. "17 results for 'containers') and the view is missing the left filtering option and therefore the ability to reset my search to the default status (users need to go back to the main store view, or search for another term).

I would suggest to use the main store view as result page, with a search that you can reset.
Quick mockup:
![mockup search results](https://user-images.githubusercontent.com/1953388/101669184-872f9c00-3a49-11eb-98f2-2eee9f732298.jpg)

We might need to break this down in UX and build.
(the "containers with attitude" on the left in the filter is just an idea, could be another way to reset it - @danielmutis please have a look when you have time).

**Comment by solazio** [comment]
@danielmutis @tbille @jkfran @clagom perhaps we can have a meeting today to discuss how we could achieve this so the page loading time is not affected and is also future proof.

**Comment by danielmutis** [comment]
I have reviewed this and I came up with a few possible solutions for how to clear the search. 

1. Just have an X on the right side of the search field. This goes together with an couple options for the results number header:
[1.1 All muted header.](https://zpl.io/bWlkLvP)
[1.2 Muted header with bolder more noticeable search term.](https://zpl.io/V17wlrZ)

[2. Having some sort of search reset on the label so it's closer to the results.](https://zpl.io/bowZ94X) This would help users identify quicker a way of clearing results than going back to the search bar which is quite far at the top.

[3. Visualising the search term as a chip](https://zpl.io/blQZPvv), with an X to be able to reset the search on the label. 

I think the option of having a filter appear on the left hand side can be potentially confusing, since it is not immediately clear that the filter should be connected to the search bar. One could argue it wouldn't be the expected behaviour for it to affect the side bar. 
Most websites will just keep the searched word on the bar in combination with a results header, as in option 1 ([amazon](https://www.amazon.co.uk/s?k=potato+ricer&i=kitchen&rh=n%3A3147491&dc&crid=1TNTYK0QNSMY0&qid=1607958387&rnid=1632651031&sprefix=pot%2Caps%2C167&ref=sr_nr_p_89_1), [ebay](https://www.ebay.co.uk/sch/i.html?_from=R40&_nkw=trainers&_sacat=0&rt=nc&Shoe%2520Size=UK%25206&_dcat=15709), [apple](https://www.apple.com/uk/search/Phone+Case?src=globalnav)). However, their search bar is much closer to the results, so I'd suggest [removing the hero section on search](https://zpl.io/anjYp6r).

**Comment by clagom** [comment]
Nice options @danielmutis 👍
I agree with removing the hero too

**Comment by danielmutis** [comment]
After Product Design Review I have uploaded a [new design](https://zpl.io/VDXWN1W). The solution is:

- Remove hero in search results
- Make the label on the results "N search results for **'search term'**"
- Add an X at the end of the search which would delete the words in the field so they can submit a new search

**Comment by clagom** [comment]
Did we define what happens when users click on a filter on the left while still looking at "Kubernetes" results? "Kubernetes" stays relevant?

**Comment by danielmutis** [comment]
So, the label won't be changed when they click a filter, as they already have feedback on what filters have been selected. The number of results is the only thing that will change. This is similar to all of the examples I mentioned earlier (Ebay and Amazon).

**Comment by clagom** [comment]
Sounds good, let's make sure this intended behaviour is maintained during the implementation phase or specs ;)

**Comment by jkfran** [comment]
This was fixed
