### ISSUE TITLE
Cassandra page displaying incorrect information

### ISSUE THREAD

**Issue by stub42** [canonical-web-and-design/charmhub.io#736]
https://charmhub.io/cassandra is listing Narinda as the maintainer of the charm, when the charm itself is maintained by the cassandra-charmers team. I believe Narinda is working on a k8s Cassandra charm. The documentation and the rest of the page is for the older IaaS version of the charm. The page lists the platform as Ubuntu 16.04, when this is the worst supported alternative. The charms metadata.yaml declares support in preferred order (per Juju) for focal, bionic, xenial and finally trusty (16.04).

**Comment by stub42** [comment]
Probably a dupe of https://github.com/canonical-web-and-design/charmhub.io/issues/724

**Comment by stub42** [comment]
Consider a richer hierarchy, eg. charmhub.io/cassandra/trusty, charmhub.io/cassandra/focal charmhub.io/cassandra/k8s. This would allow pages to remain for old versions of the charm (which still work), even after support has been dropped for older series from newer versions of the charm. Edge and stable channels may be appropriate to map in too.

**Comment by Roadmaster** [comment]
I've completed the first half of the fix which is blasting away the existing charmhub cassandra (based on the machine charm), and importing Narinder's oddly-named k8s-cassandra one instead (as the top-level https://charmhub.io/cassandra charm).

Since toplevelness/promulgation is different now between charmstore and charmhub, a mapping to update the instructions needs to be done by Toto please. I've updated the coordination spreadsheet with the new data, which is simply that the charmhub charm is now named "cassandra" instead of "k8s-cassandra" - the charmstore target remains the same.
