### ISSUE TITLE
https://charmhub.io/telegraf confused about where to deploy

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/charmhub.io#790]
https://charmhub.io/telegraf says `juju deploy cs:~telegraf-charmers/telegraf-k8s` but claims to support 20.04 LTS, 18.04 LTS, 16.04 LTS. It seems to be another one that's mixing up k8s charms with IaaS charms.

**Comment by Roadmaster** [comment]
Says here we should we importing `~telegraf-charmers/telegraf-k8s` as `telegraf`, which seems to be correct. I'll nuke it from the database and reimport it.

**Comment by Roadmaster** [comment]
My log says we correctly skipped the undesired currently-promulgated-in-charmstore charm:

`INFO  Name clashes with a toplevel charm. Skipped telegraf(~llama-charmers/telegraf`)

That one is at revision 39 which is what I see in charmhub.io as well.

It looks like I do need to remove the existing, old charm so the new one can be imported, otherwise:
```
2021-01-21 14:52:57,544 DEBUG Already registered: charm telegraf WUIj9keqJBgo29PCR0i7SKV1qXypEsOb
2021-01-21 14:52:57,573 DEBUG 6 revisions already exists for WUIj9keqJBgo29PCR0i7SKV1qXypEsOb
2021-01-21 14:52:57,573 ERROR snaprevs revision=34 not found in mongo revs [0, 1, 2, 3, 4]. Failed telegraf(~telegraf-charmers/telegraf-k8s)
```

I'll do so as time permits.

**Comment by Roadmaster** [comment]
Please check https://charmhub.io/telegraf, it's been nuked and recreated with correct data.
