### ISSUE TITLE
PostgreSQL K8s is missing icon

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/charmhub.io#801]
https://charmhub.io/postgresql-k8s is missing an icon. It's based on https://jaas.ai/u/postgresql-charmers/postgresql-k8s which has an icon, so not sure why it's missing.

**Comment by Roadmaster** [comment]
`curl https://api.charmhub.io/v2/charms/info/grafana?fields=result.media | jq .` <- this has an icon OK

these do not:

`curl https://api.charmhub.io/v2/charms/info/postgresql?fields=result.media | jq .`
`curl https://api.charmhub.io/v2/charms/info/postgresql-k8s?fields=result.media | jq .`

I checked and the actual charm zip/payload does have icon.svg. Sounds like our known weird-default-release determination issue.

**Comment by mthaddon** [comment]
This now seems to affect every charm, fwiw, eg. https://charmhub.io/mattermost https://charmhub.io/discourse

**Comment by Roadmaster** [comment]
An importer mishap nuked most of the icons and readmes, but has now been corrected. postgresql-k8s now has an icon, and so do pretty much all the other charms (we even fixed the corrupt grafana icon and other missing icons due to svg conversion trouble) https://charmhub.io/postgresql-k8s This issue can be closed.
