### ISSUE TITLE
cs prefix incorrect

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/charmhub.io#952]
When viewing a charm the deploy code is not correct.

`juju deploy cs:ceph-mon` should be `juju deploy ceph-mon` which works across all Juju versions. But if you wanted to include the prefix, for Juju 2.9 it is `ch` not `cs` any longer.

![Screen Shot 2021-04-26 at 3 24 52 PM](https://user-images.githubusercontent.com/532033/116152972-d9ddbd80-a6a3-11eb-8857-0a22ddf03f19.png)

**Comment by anthonydillon** [comment]
Interesting, I tried the command on charmhub which didn't work as you mentioned: `juju deploy cs:mattermost-charmers-mattermost`.
![Screenshot_20210426-235304.jpg](https://user-images.githubusercontent.com/1413534/116160855-ae31f600-a6ea-11eb-9224-63afc4f4f08d.jpg)

Then removed `cs:` and that still didn't work.

**Comment by Roadmaster** [comment]
@anthonydillon which version of juju are you using?

**Comment by anthonydillon** [comment]
Version 2.8.7 but why would that matter?

I thought the issue was clear.

I ran the command provided by charmhub. Which failed.

I would expect it to deploy the application in question.

**Comment by Roadmaster** [comment]
It matters because you then said "Then removed cs: and that still didn't work.", and it should - *if* you're using juju 2.9rc11 or newer, which you're not. So that explains why removing the prefix didn't work.

The other reason is that charmhub instructions with `cs:` prefix are incorrect because charm names are different between charmstore and charmhub, due to the move to the flat charm namespace. removing the `cs:` will only work for charms that were promulgated in charmstore, which are the only ones for which the name is the same in both charmstore and charmhub.

In order for the deploy instructions to be correct, the `cs:` prefix must be removed from all of them. The instructions should then work *with juju 2.9rc11 or newer*.

**Comment by anthonydillon** [comment]
To be clearer, I asked why should that matter because I was sure there would some work to do on charmhub to get this to work. 

If we are expecting a lot of new users during kubecon we need to make this clear even if the UX is not good for current Juju users.

**Comment by tbille** [comment]
The `cs:` is now removed and we have a notification on the charm pages with a warning to use juju 2.9. Closing this issue.
